# Generated by Django 5.2 on 2025-04-30 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('numero_semana', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_dia', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('numero_estado', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('numero_servicio', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosEstilista',
            fields=[
                ('numero_combinacion', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('cedula_estilista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='users.estilista')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilistas', to='appointment.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('numero_cita', models.BigIntegerField(default=1, primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_finalizacion', models.TimeField()),
                ('dia_mes', models.PositiveSmallIntegerField()),
                ('hora_inicio_agendacion', models.TimeField()),
                ('hora_finalizacion_agendacion', models.TimeField()),
                ('calificacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuario')),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointment.diasemana')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointment.estado')),
                ('servicios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.serviciosestilista')),
            ],
        ),
    ]
